using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Application.common
{
    public class Maps
    {
        public readonly string[,,] Default = 
        {
            {
                {
                    "phenylalanine",
                    "phenylalanine",
                    "leucine",
                    "leucine"
                },
                {
                    "serine",
                    "serine",
                    "serine",
                    "serine"
                },
                {
                    "tyrosine",
                    "tyrosine",
                    "stop",
                    "stop"
                },
                {
                    "cysteine",
                    "cysteine",
                    "stop",
                    "tryptophan"
                }
            },
            {
                {
                    "leucine",
                    "leucine",
                    "leucine",
                    "leucine"
                },
                {
                    "proline",
                    "proline",
                    "proline",
                    "proline"
                },
                {
                    "histidine",
                    "histidine",
                    "glutamine",
                    "glutamine"
                },
                {
                    "arginine",
                    "arginine",
                    "arginine",
                    "arginine"
                }
            },
            {
                {
                    "isoleucine",
                    "isoleucine",
                    "isoleucine",
                    "methionine"
                },
                {
                    "threonine",
                    "threonine",
                    "threonine",
                    "threonine"
                },
                {
                    "asparagine",
                    "asparagine",
                    "lysine",
                    "lysine"
                },
                {
                    "serine",
                    "serine",
                    "arginine",
                    "arginine"
                }
            },
            {
                {
                    "valine",
                    "valine",
                    "valine",
                    "valine"
                },
                {
                    "alanine",
                    "alanine",
                    "alanine",
                    "alanine"
                },
                {
                    "aspartate",
                    "aspartate",
                    "glutamate",
                    "glutamate"
                },
                {
                    "glycine",
                    "glycine",
                    "glycine",
                    "glycine"
                }
            }
        };
    }
}